-- =========================================================================
-- MEDIVAULT INDIA: STARTER / COMMON MEDICINE DATABASE (VERIFIED SEED)
-- =========================================================================

-- References
INSERT INTO public.references (id, source_name, source_type, title, url) VALUES
('11111111-0000-0000-0000-000000000001', 'Indian Pharmacopoeia (IP)', 'regulatory', 'Indian Pharmacopoeia Commission Monographs', 'https://ipc.gov.in'),
('11111111-0000-0000-0000-000000000002', 'CDSCO National List of Essential Medicines', 'regulatory', 'NLEM India Reference', 'https://cdsco.gov.in'),
('11111111-0000-0000-0000-000000000003', 'Goodman & Gilman / KD Tripathi Pharmacology', 'clinical', 'Essentials of Medical Pharmacology 8th Ed', NULL)
ON CONFLICT (id) DO NOTHING;

-- Core Manufacturers
INSERT INTO public.manufacturers (id, name, country, verified) VALUES
('22222222-0000-0000-0000-000000000001', 'Cipla Ltd', 'India', true),
('22222222-0000-0000-0000-000000000002', 'Sun Pharmaceutical Industries Ltd', 'India', true),
('22222222-0000-0000-0000-000000000003', 'Dr. Reddy''s Laboratories', 'India', true),
('22222222-0000-0000-0000-000000000004', 'Abbott Healthcare Pvt Ltd', 'India', true),
('22222222-0000-0000-0000-000000000005', 'GSK Pharmaceuticals India', 'India', true),
('22222222-0000-0000-0000-000000000006', 'Torrent Pharmaceuticals', 'India', true),
('22222222-0000-0000-0000-000000000007', 'Alkem Laboratories Ltd', 'India', true),
('22222222-0000-0000-0000-000000000008', 'Lupin Ltd', 'India', true),
('22222222-0000-0000-0000-000000000009', 'Micro Labs Ltd', 'India', true)
ON CONFLICT (id) DO NOTHING;

-- Hierarchical Drug Classes
INSERT INTO public.drug_classes (id, name, description, classification_type, simple_definition, hinglish_explanation) VALUES
('33333333-0000-0000-0000-000000000001', 'Analgesics & Antipyretics', 'Pain and fever reducing medicines', 'therapeutic', 'Medicines that relieve pain and reduce elevated body temperature.', 'Pain aur fever ko kam karne wali davaiyan.'),
('33333333-0000-0000-0000-000000000002', 'NSAIDs', 'Non-Steroidal Anti-Inflammatory Drugs', 'pharmacological', 'Medicines that reduce pain, fever, and inflammation by blocking COX enzymes.', 'Non-steroidal davaiyan jo dard aur soojan (inflammation) ko COX enzyme block karke rokti hain.'),
('33333333-0000-0000-0000-000000000003', 'Proton Pump Inhibitors (PPIs)', 'Gastric acid suppressants', 'pharmacological', 'Medicines that strongly reduce stomach acid production by inhibiting the H+/K+ ATPase pump.', 'Pet ke acid secretion ko H+/K+ pump block karke kam karne wali medicines.'),
('33333333-0000-0000-0000-000000000004', 'Angiotensin II Receptor Blockers (ARBs)', 'Antihypertensives blocking AT1 receptors', 'pharmacological', 'Medicines that relax blood vessels by blocking angiotensin II from binding to receptors.', 'Blood pressure kam karne ke liye Angiotensin II ke action ko block karne wali medicines.'),
('33333333-0000-0000-0000-000000000005', 'Calcium Channel Blockers (CCBs)', 'Vascular smooth muscle relaxants', 'pharmacological', 'Medicines that inhibit calcium entry into cardiac and vascular smooth muscle.', 'Blood vessels ko relax karke high BP aur angina ko control karne wali davaiyan.'),
('33333333-0000-0000-0000-000000000006', 'HMG-CoA Reductase Inhibitors (Statins)', 'Lipid-lowering agents', 'pharmacological', 'Medicines that reduce LDL cholesterol synthesis in the liver.', 'Liver mein cholesterol synthesis ko block karke bad cholesterol (LDL) kam karne wali medicines.'),
('33333333-0000-0000-0000-000000000007', 'Beta-Lactam Antibiotics (Penicillins)', 'Bacterial cell-wall synthesis inhibitors', 'pharmacological', 'Antibacterial medicines that disrupt bacterial cell wall peptidoglycan synthesis.', 'Bacteria ki cell wall ko todkar unhe destroy karne wali antibiotics.'),
('33333333-0000-0000-0000-000000000008', 'Macrolide Antibiotics', 'Bacterial protein synthesis 50S inhibitors', 'pharmacological', 'Antibiotics that inhibit bacterial protein synthesis by binding to 50S ribosomal subunit.', 'Bacteria ke protein production ko 50S ribosome par bind karke rokne wali antibiotics.'),
('33333333-0000-0000-0000-000000000009', 'Tetracyclines', 'Bacterial protein synthesis 30S inhibitors', 'pharmacological', 'Broad-spectrum bacteriostatic antibiotics binding to 30S subunit.', 'Bacteria ke growth ko 30S ribosome block karke rokne wali broad-spectrum medicines.'),
('33333333-0000-0000-0000-000000000010', 'Biguanides (Antidiabetic)', 'Hepatic gluconeogenesis inhibitors & insulin sensitizers', 'pharmacological', 'Oral antihyperglycemic agents that lower blood glucose without stimulating insulin secretion.', 'Liver se extra glucose production kam karne aur insulin sensitivity badhane wali medicine.'),
('33333333-0000-0000-0000-000000000011', 'Antiemetics (5-HT3 Antagonists)', 'Serotonin receptor blockers for nausea/vomiting', 'pharmacological', 'Medicines that block serotonin 5-HT3 receptors in CTZ and gut to stop vomiting.', 'Vomiting aur nausea ko control karne ke liye brain aur gut ke serotonin receptors ko block karne wali medicine.'),
('33333333-0000-0000-0000-000000000012', 'Second-Generation Antihistamines (H1)', 'Non-sedating allergic response blockers', 'pharmacological', 'Medicines that block peripheral H1 receptors with minimal blood-brain barrier penetration.', 'Allergy, itching aur runny nose ko bina zyada neend laye control karne wali medicines.'),
('33333333-0000-0000-0000-000000000013', 'Short-Acting Beta-2 Agonists (SABA)', 'Bronchodilators', 'pharmacological', 'Medicines that stimulate beta-2 receptors in airway smooth muscle causing rapid bronchodilation.', 'Asthma aur breathing problem mein saans ki nali ko jaldi kholne wali bronchodilator medicine.'),
('33333333-0000-0000-0000-000000000014', 'Antiplatelet Agents', 'Platelet aggregation inhibitors', 'pharmacological', 'Medicines that prevent blood clots by inhibiting platelet activation.', 'Blood clots banne se rokne ke liye platelets ko aapas mein chipakne se rokne wali medicines.'),
('33333333-0000-0000-0000-000000000015', 'Thyroid Hormone Analogues', 'Synthetic T4 replacement', 'pharmacological', 'Synthetic levothyroxine sodium identical to endogenous thyroid thyroxine.', 'Thyroid hormone deficiency (hypothyroidism) ko pura karne ke liye di jaane wali synthetic T4 hormone.')
ON CONFLICT (id) DO NOTHING;

-- 20 Verified Common Starter Medicines
INSERT INTO public.medicines (
  id, generic_name, display_name, active_ingredient, salt, description, strength, dosage_forms, routes,
  mechanism_of_action, pharmacodynamics, absorption, distribution, metabolism, excretion,
  bioavailability, half_life, protein_binding, volume_of_distribution, clearance, onset, duration,
  indications, contraindications, warnings, precautions,
  common_adverse_effects, serious_adverse_effects, food_interactions, monitoring,
  pregnancy, lactation, pediatric, geriatric, renal, hepatic,
  advantages, disadvantages, key_points, memory_trick, key_suffix,
  verification_status, source, last_verified, data_version
) VALUES
(
  '44444444-0000-0000-0000-000000000001',
  'Paracetamol',
  'Paracetamol (Acetaminophen)',
  'Paracetamol',
  'N-acetyl-p-aminophenol',
  'First-line antipyretic and mild-to-moderate analgesic with minimal peripheral anti-inflammatory action.',
  '500 mg, 650 mg',
  ARRAY['Tablet', 'Syrup', 'Suspension', 'IV Infusion', 'Suppository'],
  ARRAY['Oral', 'Intravenous', 'Rectal'],
  'Centrally inhibits prostaglandin synthesis likely via COX-3 / CNS peroxidase inhibition and activates descending serotonergic pathways.',
  'Reduces body temperature in pyrexia via hypothalamic thermoregulatory center action; elevates pain threshold.',
  'Rapid and almost complete from the gastrointestinal tract.',
  'Widely distributed throughout most body tissues.',
  'Hepatic (90-95%) via glucuronidation and sulfation; minor fraction metabolized by CYP2E1 to toxic NAPQI (detoxified by glutathione).',
  'Renal (>90% as inactive conjugates within 24 hours).',
  '~88%',
  '1.5 to 2.5 hours',
  '10-25% at therapeutic concentrations',
  '~0.9 L/kg',
  '~5 mL/min/kg',
  '30 to 60 minutes (oral)',
  '4 to 6 hours',
  ARRAY['Pyrexia (fever)', 'Mild to moderate pain', 'Headache', 'Myalgia', 'Dental pain', 'Osteoarthritis adjunctive pain'],
  ARRAY['Severe acute hepatic failure', 'Hypersensitivity to paracetamol'],
  ARRAY['Do not exceed 4000 mg/day in adults due to risk of severe hepatotoxicity', 'Caution with concurrent paracetamol-containing products'],
  ARRAY['Chronic alcoholism', 'Severe malnutrition', 'G6PD deficiency', 'Chronic liver disease'],
  ARRAY['Nausea', 'Mild rash', 'Epigastric discomfort'],
  ARRAY['Hepatotoxicity / acute liver necrosis in overdose', 'Stevens-Johnson syndrome (rare)', 'Thrombocytopenia (rare)'],
  ARRAY['Avoid heavy alcohol consumption (induces CYP2E1 and depletes glutathione)'],
  ARRAY['Liver function tests in prolonged high-dose therapy or suspected overdose'],
  'Category B / generally considered safe when used at recommended therapeutic doses.',
  'Compatible with breastfeeding; excreted in breast milk in small clinically insignificant amounts.',
  'Dosed by weight (10-15 mg/kg every 4-6 hours; max 60 mg/kg/day).',
  'Use lower daily maximums in frail elderly or those with hepatic impairment.',
  'Dose interval extension to 6-8 hours in severe renal impairment (CrCl < 10 mL/min).',
  'Dose reduction mandatory in chronic hepatic impairment; contraindicated in acute severe liver failure.',
  ARRAY['Safe gastric profile compared to NSAIDs', 'No antiplatelet effect', 'Safe in children and pregnancy when indicated'],
  ARRAY['Minimal anti-inflammatory action', 'Overdose carries high risk of fatal hepatic failure'],
  ARRAY['Antidote for toxicity is N-Acetylcysteine (NAC)', 'Max adult dose 4000 mg/24h (often restricted to 3000 mg/24h clinically)'],
  'Para = Pure Antipyretic; Acetylcysteine saves the liver.',
  '-mol',
  'verified',
  'Indian Pharmacopoeia & WHO NLEM',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000002',
  'Ibuprofen',
  'Ibuprofen',
  'Ibuprofen',
  '2-(4-isobutylphenyl)propionic acid',
  'Widely used non-selective NSAID providing analgesic, antipyretic, and anti-inflammatory relief.',
  '200 mg, 400 mg, 600 mg',
  ARRAY['Tablet', 'Suspension', 'Capsule', 'Gel'],
  ARRAY['Oral', 'Topical'],
  'Non-selectively and reversibly inhibits cyclooxygenase-1 (COX-1) and cyclooxygenase-2 (COX-2) enzymes, reducing prostaglandin synthesis.',
  'Suppresses inflammatory erythema, edema, hyperalgesia, and pain mediator sensitization.',
  'Rapidly absorbed from gastrointestinal tract (peak plasma 1-2 hours).',
  'Highly bound to albumin; penetrates into synovial fluid.',
  'Hepatic oxidation via CYP2C9 and CYP2C8 to inactive metabolites.',
  'Renal (90% excreted as inactive metabolites and glucuronides).',
  '~80-90%',
  '1.8 to 2.0 hours',
  '99% bound to plasma proteins',
  '~0.12 to 0.15 L/kg',
  '~3.0 L/h',
  '30 to 45 minutes',
  '6 to 8 hours',
  ARRAY['Inflammatory arthritis', 'Dysmenorrhea', 'Dental pain', 'Musculoskeletal injury', 'Fever unresponsive to paracetamol'],
  ARRAY['Active peptic ulcer disease', 'History of NSAID-induced GI bleeding/perforation', 'Severe heart failure', 'Third-trimester pregnancy'],
  ARRAY['Increased risk of cardiovascular thrombotic events', 'GI ulceration and bleeding can occur without warning'],
  ARRAY['Hypertension', 'Dehydration (risk of acute renal impairment)', 'Asthma (risk of bronchospasm in aspirin-sensitive patients)'],
  ARRAY['Dyspepsia', 'Heartburn', 'Nausea', 'Abdominal pain', 'Dizziness'],
  ARRAY['Gastrointestinal bleeding', 'Acute kidney injury', 'Bronchospasm', 'Severe cutaneous reactions'],
  ARRAY['Take with food or milk to minimize gastric distress'],
  ARRAY['Blood pressure', 'Serum creatinine / renal function in chronic users', 'Hemoglobin / stool for occult blood'],
  'Avoid in 3rd trimester (premature closure of fetal ductus arteriosus). Use with caution in 1st/2nd trimester.',
  'Compatible; very low levels excreted in human milk.',
  'Dosed by weight (5-10 mg/kg every 6-8 hours; max 40 mg/kg/day); not recommended under 3 months/5 kg without specialist.',
  'Higher susceptibility to renal and GI adverse effects; start at lowest effective dose.',
  'Avoid in severe renal failure; caution in mild-moderate due to fluid retention and reduced GFR.',
  'Caution in hepatic dysfunction; hepatic clearance is mediated via CYP2C9.',
  ARRAY['Effective dual analgesic and anti-inflammatory properties', 'Favorable GI safety ratio among non-selective NSAIDs at lower doses'],
  ARRAY['Ulcerogenic potential', 'Cardiorenal risk at sustained high doses'],
  ARRAY['Always check for history of asthma before prescribing NSAIDs', 'Do not co-prescribe two oral NSAIDs simultaneously'],
  'Ibu-PRO-fen = PROstaglandin inhibitor.',
  '-profen',
  'verified',
  'Indian Pharmacopoeia & KD Tripathi',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000003',
  'Diclofenac',
  'Diclofenac Sodium / Potassium',
  'Diclofenac',
  '2-[2-(2,6-dichloroanilino)phenyl]acetic acid',
  'Potent analgesic and anti-inflammatory NSAID with preferential COX-2 inhibition profile and tissue accumulation.',
  '50 mg, 75 mg, 100 mg SR',
  ARRAY['Tablet', 'Capsule', 'Injection (IM/IV)', 'Topical Gel', 'Eye Drops', 'Suppository'],
  ARRAY['Oral', 'Intramuscular', 'Intravenous', 'Topical', 'Ophthalmic'],
  'Potently inhibits COX-1 and COX-2 enzymes; also reduces intracellular arachidonate concentrations in leukocytes.',
  'Pronounced anti-inflammatory and analgesic efficacy; significant concentration in synovial fluid.',
  'Rapidly absorbed; undergoes ~50% first-pass hepatic metabolism.',
  'Concentrates selectively in inflamed synovial fluids and articular tissue.',
  'Hepatic glucuronidation and CYP2C9 hydroxylation.',
  '65% urinary excretion, 35% biliary excretion.',
  '~50-60% (due to first-pass metabolism)',
  '1.2 to 2 hours (longer in synovial fluid)',
  '>99.5% bound to albumin',
  '~0.12 to 0.55 L/kg',
  '~16 L/h',
  '20-30 min (potassium salt); 30-60 min (sodium)',
  '6 to 8 hours (standard); up to 24 hours (sustained release)',
  ARRAY['Osteoarthritis', 'Rheumatoid arthritis', 'Ankylosing spondylitis', 'Acute musculoskeletal pain', 'Post-operative pain', 'Renal colic'],
  ARRAY['Active GI ulceration', 'Established ischemic heart disease', 'Peripheral arterial disease', 'Cerebrovascular disease', 'Severe heart failure'],
  ARRAY['Highest cardiovascular risk among traditional non-selective NSAIDs; use lowest effective dose for shortest duration'],
  ARRAY['Hepatic transaminase elevation occurs in up to 15% of patients on chronic therapy', 'Renal function monitoring mandatory in elderly'],
  ARRAY['Epigastric pain', 'Nausea', 'Diarrhea', 'Headache', 'Dizziness'],
  ARRAY['GI ulceration/perforation', 'Cardiovascular thrombotic events', 'Hepatotoxicity (ALT/AST rise)', 'Renal papillary necrosis'],
  ARRAY['Take immediately after meals to reduce gastric irritation'],
  ARRAY['Baseline and periodic liver function tests (LFTs)', 'Renal function and blood pressure'],
  'Contraindicated in third trimester. Avoid throughout pregnancy unless essential.',
  'Excreted in small amounts in breast milk; alternative NSAIDs preferred.',
  'Not routinely recommended for children under 14 years except juvenile idiopathic arthritis.',
  'High risk of GI ulceration and fluid retention; close observation required.',
  'Contraindicated in severe renal failure.',
  'Contraindicated in severe hepatic impairment; monitor transaminases regularly.',
  ARRAY['High potency for joint inflammation and post-traumatic pain', 'Available in multiple topical and parenteral formulations'],
  ARRAY['Higher risk of cardiac thrombotic events and transaminitis than ibuprofen'],
  ARRAY['Diclofenac potassium acts faster than sodium for acute pain relief'],
  'DICLO = DArD (pain) + Joint inflammation target.',
  '-fenac',
  'verified',
  'CDSCO & Indian Pharmacopoeia',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000004',
  'Amoxicillin',
  'Amoxicillin',
  'Amoxicillin Trihydrate',
  '(2S,5R,6R)-6-[[(2R)-2-amino-2-(4-hydroxyphenyl)acetyl]amino]-3,3-dimethyl-7-oxo-4-thia-1-azabicyclo[3.2.0]heptane-2-carboxylic acid',
  'Moderate-spectrum bactericidal aminopenicillin with superior oral absorption compared to ampicillin.',
  '250 mg, 500 mg',
  ARRAY['Capsule', 'Tablet', 'Dry Syrup / Oral Suspension'],
  ARRAY['Oral'],
  'Inhibits bacterial cell wall synthesis by binding to penicillin-binding proteins (PBPs), causing lysis of growing bacteria.',
  'Bactericidal activity against susceptible Gram-positive and select Gram-negative organisms (Streptococcus, Enterococcus, H. influenzae).',
  'Stable in gastric acid; 75-90% absorbed independently of food.',
  'Good distribution into body fluids, bile, sputum, and middle ear fluid; poor CSF penetration across intact meninges.',
  'Limited hepatic metabolism (~10-25% converted to penicilloic acid).',
  'Predominantly renal via tubular secretion and glomerular filtration.',
  '~74-92%',
  '1 to 1.5 hours',
  '~17-20%',
  '~0.3 L/kg',
  '~250-300 mL/min',
  '1 to 2 hours',
  '6 to 8 hours',
  ARRAY['Acute otitis media', 'Streptococcal pharyngitis', 'Community-acquired pneumonia', 'Uncomplicated urinary tract infections', 'H. pylori eradication regimens'],
  ARRAY['History of severe allergic/anaphylactic reaction to penicillins or beta-lactams'],
  ARRAY['Risk of severe Clostridioides difficile-associated diarrhea', 'Avoid in infectious mononucleosis (high risk of non-allergic maculopapular rash)'],
  ARRAY['Adjust dosing in renal impairment', 'Maintain adequate fluid intake to avoid crystalluria at high doses'],
  ARRAY['Diarrhea', 'Nausea', 'Skin rash', 'Vomiting', 'Oral candidiasis'],
  ARRAY['Anaphylaxis / Angioedema', 'Pseudomembranous colitis', 'Erythema multiforme', 'Interstitial nephritis'],
  ARRAY['Food does not significantly impair absorption, unlike ampicillin'],
  ARRAY['Monitor renal function in prolonged therapy; observe for hypersensitivity reactions'],
  'Category B / generally considered safe during pregnancy.',
  'Compatible; small amounts excreted in milk (may cause loose stools or candidiasis in infant).',
  'Standard pediatric dosing: 25-45 mg/kg/day in divided doses (up to 80-90 mg/kg/day in high-dose otitis media protocols).',
  'Dose adjustment based on renal clearance.',
  'Dosing interval extension required if GFR < 30 mL/min.',
  'No specific dose adjustments required unless combined with clavulanate.',
  ARRAY['Excellent oral bioavailability not impaired by food', 'Safe safety profile in pregnant and pediatric patients'],
  ARRAY['Susceptible to degradation by beta-lactamase producing organisms (e.g., S. aureus, Klebsiella)'],
  ARRAY['Always complete the full prescribed antimicrobial course to prevent resistance'],
  'Amox = Active against Mobile bacteria, destroyed by lactaMASE unless protected.',
  '-cillin',
  'verified',
  'Indian Pharmacopoeia & WHO NLEM',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000005',
  'Amoxicillin + Clavulanic Acid',
  'Amoxicillin and Potassium Clavulanate (Co-Amoxiclav)',
  'Amoxicillin Trihydrate + Potassium Clavulanate',
  'Amoxicillin + Potassium Clavulanate',
  'Beta-lactam antibiotic potentiated with a beta-lactamase inhibitor to overcome bacterial resistance.',
  '625 mg (500mg/125mg), 375 mg, 1000 mg ER, 1.2 g Injection',
  ARRAY['Tablet', 'Dry Syrup / Oral Suspension', 'Injection (IV)'],
  ARRAY['Oral', 'Intravenous'],
  'Clavulanic acid acts as a suicide inhibitor of Class A beta-lactamases, protecting amoxicillin from enzymatic degradation.',
  'Restores amoxicillin antimicrobial activity against beta-lactamase-producing S. aureus, H. influenzae, E. coli, and Bacteroides.',
  'Both components well absorbed; taking at start of meal improves clavulanate absorption and reduces GI intolerance.',
  'Widely distributed into tissues, secretions, and peritoneal fluid.',
  'Amoxicillin is minimally metabolized; clavulanic acid is extensively metabolized (~50%).',
  'Renal excretion of both active components.',
  'Amoxicillin ~90%, Clavulanate ~60-70%',
  '~1 hour (amoxicillin) / ~1 hour (clavulanate)',
  'Amoxicillin ~18%, Clavulanate ~25%',
  '~0.3 L/kg',
  '~25 L/h',
  '1 to 2 hours',
  '8 to 12 hours',
  ARRAY['Acute bacterial sinusitis', 'Otitis media refractory to amoxicillin', 'Bite wounds', 'Community-acquired pneumonia', 'Complicated urinary tract infections', 'Skin & soft tissue infections'],
  ARRAY['History of penicillin anaphylaxis', 'History of amoxicillin/clavulanate-associated cholestatic jaundice or hepatic dysfunction'],
  ARRAY['Risk of cholestatic jaundice (predominantly attributed to clavulanic acid component)', 'C. difficile colitis'],
  ARRAY['Take with meals to reduce gastrointestinal distress', 'Monitor hepatic enzymes in prolonged courses (>14 days)'],
  ARRAY['Diarrhea (frequent)', 'Nausea', 'Vomiting', 'Candidiasis', 'Abdominal cramps'],
  ARRAY['Cholestatic jaundice / hepatitis', 'Severe anaphylactoid reaction', 'Stevens-Johnson syndrome'],
  ARRAY['Administer at start of a meal for optimal absorption and tolerability'],
  ARRAY['Hepatic function tests (ALT/AST/Alkaline Phosphatase) if therapy exceeds 14 days'],
  'Category B / safe when clinically indicated.',
  'Compatible; excreted in small amounts in breast milk.',
  'Pediatric suspension dosed based on amoxicillin component (25-45 mg/kg/day divided 12-hourly).',
  'Monitor renal function for dose adjustments.',
  'Contraindicated/adjusted when GFR < 30 mL/min (avoid 875/125 or 1000/125 formulations; use 500/125 with adjusted interval).',
  'Use with extreme caution; contraindicated in patients with past Co-Amoxiclav-induced liver injury.',
  ARRAY['Broadened antimicrobial coverage including beta-lactamase producers and anaerobes', 'Gold standard empiric oral antibiotic'],
  ARRAY['Significantly higher incidence of diarrhea and cholestatic hepatitis than amoxicillin alone'],
  ARRAY['Ratios matter: 4:1 and 7:1 amoxicillin:clavulanate oral formulations have distinct dosing regimens'],
  'Amox + CLAV = Clavulanate LInks And Vanquishes Beta-lactamase.',
  '-cillin',
  'verified',
  'Indian Pharmacopoeia & CDSCO',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000006',
  'Azithromycin',
  'Azithromycin',
  'Azithromycin Dihydrate',
  '9-deoxy-9a-aza-9a-methyl-9a-homoerythromycin A',
  'Azalide subclass macrolide antibiotic characterized by extensive tissue distribution and prolonged elimination half-life.',
  '250 mg, 500 mg',
  ARRAY['Tablet', 'Suspension', 'IV Infusion', 'Eye Drops'],
  ARRAY['Oral', 'Intravenous', 'Ophthalmic'],
  'Binds reversibly to the 50S ribosomal subunit of susceptible microorganisms, inhibiting transpeptidation and protein synthesis.',
  'Time-dependent bacteriostatic activity against atypical respiratory pathogens (Mycoplasma, Chlamydia, Legionella) and Gram-positives.',
  'Rapidly absorbed from GI tract but oral bioavailability is limited by first-pass and tissue uptake.',
  'Remarkable tissue penetration (tissue concentrations 10-100x higher than serum); concentrated in phagocytes and lysosomes.',
  'Demethylation in liver to inactive metabolites; does not significantly inhibit CYP3A4 (unlike erythromycin).',
  'Predominantly biliary / fecal elimination (>50% as unchanged drug); only 6-12% excreted in urine.',
  '~37%',
  '68 to 72 hours (tissue half-life)',
  '7-50% (inversely proportional to concentration)',
  '~31 L/kg (very large volume of distribution)',
  '~630 mL/min',
  '2 to 3 hours',
  '24+ hours (allows once-daily 3-5 day regimens with extended tissue duration)',
  ARRAY['Atypical community-acquired pneumonia', 'Acute bacterial exacerbation of chronic bronchitis', 'Chlamydia trachomatis urethritis/cervicitis', 'Enteric fever (typhoid)', 'Skin infections'],
  ARRAY['Hypersensitivity to macrolides', 'History of cholestatic jaundice/hepatic dysfunction with prior azithromycin'],
  ARRAY['QT prolongation and risk of Torsades de Pointes (caution in patients with hypokalemia or cardiac arrhythmias)'],
  ARRAY['Myasthenia gravis exacerbation', 'Overuse drives macrolide resistance in Streptococcus pneumoniae'],
  ARRAY['Nausea', 'Diarrhea', 'Abdominal pain', 'Vomiting', 'Flatulence'],
  ARRAY['QT interval prolongation', 'Cholestatic hepatitis / hepatic failure', 'C. difficile-associated colitis', 'Anaphylaxis'],
  ARRAY['Can be taken with or without food, though food improves tolerability of some formulations'],
  ARRAY['Baseline ECG in cardiac patients; serum electrolytes in high-risk patients'],
  'Category B / generally safe when indicated during pregnancy.',
  'Compatible; low concentrations found in breast milk.',
  'Standard pediatric dosing: 10 mg/kg on day 1, followed by 5 mg/kg/day on days 2-5.',
  'Monitor for QT prolongation; no dose adjustment for mild-moderate renal decline.',
  'No dose adjustment needed for GFR > 10 mL/min; caution when GFR < 10 mL/min.',
  'Use caution in severe hepatic impairment since biliary excretion is the primary route.',
  ARRAY['Short 3-5 day courses due to long tissue residence', 'Low risk of CYP3A4 drug interactions compared to erythromycin'],
  ARRAY['Growing global and national resistance among respiratory and enteric pathogens'],
  ARRAY['3-day 500mg once-daily course provides therapeutic tissue levels for up to 7-10 days'],
  'Azithro = A-Z Coverage of Atypicals + 72-hour half-life.',
  '-thromycin',
  'verified',
  'Indian Pharmacopoeia & WHO NLEM',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000007',
  'Doxycycline',
  'Doxycycline Hyclate / Monohydrate',
  'Doxycycline',
  '(4S,4aR,5S,5aR,6R,12aS)-4-(dimethylamino)-3,5,10,12,12a-pentahydroxy-6-methyl-1,11-dioxo-1,4,4a,5,5a,6,11,12a-octahydrotetracene-2-carboxamide',
  'Long-acting synthetic tetracycline antibiotic with broad-spectrum activity against rickettsiae, atypicals, and vector-borne infections.',
  '100 mg',
  ARRAY['Capsule', 'Tablet', 'IV Infusion'],
  ARRAY['Oral', 'Intravenous'],
  'Bacteriostatic inhibitor of protein synthesis by binding to the 30S ribosomal subunit, preventing aminoacyl-tRNA attachment to the mRNA-ribosome complex.',
  'Broad-spectrum antimicrobial; additionally exhibits anti-inflammatory and matrix metalloproteinase (MMP) inhibitor properties.',
  'Virtually complete absorption (>90%) from upper GI tract.',
  'Lipophilic; penetrates well into prostate, eye, bronchial secretions, and bile.',
  'Partially metabolized in the liver (<20%).',
  'Excreted through non-renal routes: direct biliary secretion and inactive chelate diffusion across intestinal wall into feces; ~30-40% in urine.',
  '~90-100%',
  '18 to 22 hours',
  '80-90%',
  '~0.75 L/kg',
  '~30-40 mL/min',
  '1.5 to 2 hours',
  '12 to 24 hours',
  ARRAY['Scrub typhus and Rickettsial infections', 'Malaria prophylaxis and treatment (adjunct)', 'Acne vulgaris / Rosacea', 'Chlamydial infections', 'Brucellosis', 'Cholera', 'Lyme disease'],
  ARRAY['Hypersensitivity to tetracyclines', 'Pregnancy', 'Children under 8 years of age (risk of permanent tooth discoloration and enamel hypoplasia)'],
  ARRAY['Severe pill-induced esophageal ulceration if swallowed without sufficient water or before lying down', 'Photosensitivity reactions'],
  ARRAY['Space at least 2-3 hours away from iron, calcium, antacids, or dairy products (divalent cations chelate doxycycline)'],
  ARRAY['Esophageal irritation', 'Nausea', 'Vomiting', 'Photosensitivity rash', 'Epigastric discomfort'],
  ARRAY['Esophageal stricture/ulceration', 'Benign intracranial hypertension (pseudotumor cerebri)', 'Severe photosensitivity'],
  ARRAY['Chelates with calcium/iron/magnesium - avoid milk, dairy, antacids, iron supplements within 2 hours of dose'],
  ARRAY['Monitor for skin phototoxicity; inquire about pill ingestion habits and upright posture'],
  'Category D / Contraindicated (causes permanent tooth staining and inhibits fetal bone growth).',
  'Avoid prolonged use; short courses under expert supervision if no alternatives exist.',
  'Generally contraindicated in children < 8 years due to dental staining, except life-threatening scrub typhus/Rocky Mountain spotted fever.',
  'Safe without dose adjustments because excretion does not rely on renal pathways.',
  'Safe in renal failure without dose reduction (unique among tetracyclines due to intestinal excretion).',
  'Caution with co-administered hepatotoxic drugs.',
  ARRAY['Safe in renal impairment without dose adjustment', 'Drug of choice for scrub typhus and tick-borne diseases in India'],
  ARRAY['Strict swallowing protocol required (drink full glass of water and remain upright for 30 minutes) to prevent esophagitis'],
  ARRAY['Always instruct patients to take with a full glass of water and stay upright for 30 minutes'],
  'Doxy = Drink Plenty of Water + Avoid Sun (Photosensitivity) + Bone/Teeth stain.',
  '-cycline',
  'verified',
  'Indian Pharmacopoeia & ICMR Guidelines',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000008',
  'Omeprazole',
  'Omeprazole',
  'Omeprazole Magnesium',
  '5-methoxy-2-[[(4-methoxy-3,5-dimethylpyridin-2-yl)methyl]sulfinyl]-1H-benzimidazole',
  'Prototype proton pump inhibitor (PPI) providing profound and prolonged suppression of basal and stimulated gastric acid.',
  '20 mg, 40 mg',
  ARRAY['Capsule (Enteric-coated)', 'Tablet', 'IV Infusion'],
  ARRAY['Oral', 'Intravenous'],
  'Prodrug activated in the acidic canaliculi of parietal cells to a sulfenamide intermediate that irreversibly binds via disulfide bonds to H+/K+ ATPase.',
  'Increases intragastric pH (>4.0) for sustained intervals, allowing mucosal healing in ulcers and GERD.',
  'Acid-labile; formulated with enteric coating. Bioavailability increases from 40% with initial dose to 65% with repeated daily dosing.',
  'Well distributed; protein bound.',
  'Hepatic via CYP2C19 (major) and CYP3A4 to inactive hydroxy- and sulfone-omeprazole.',
  'Renal (~80%) and fecal/biliary (~20%).',
  '~40-65%',
  '0.5 to 1 hour (biological effect lasts 24-72 hours due to irreversible enzyme inactivation)',
  '~95%',
  '~0.3 L/kg',
  '~500 mL/min',
  '0.5 to 1 hour',
  '24 to 72 hours',
  ARRAY['Gastroesophageal Reflux Disease (GERD)', 'Peptic ulcer disease (Gastric and Duodenal)', 'H. pylori eradication (as part of triple regimen)', 'NSAID-associated ulcer prevention', 'Zollinger-Ellison syndrome'],
  ARRAY['Known hypersensitivity to omeprazole or substituted benzimidazoles'],
  ARRAY['Long-term use (>1 year) associated with hypomagnesemia, vitamin B12 deficiency, bone fractures, and C. difficile infections', 'May mask symptoms of gastric malignancy'],
  ARRAY['Administer 30 to 60 minutes before breakfast for maximal parietal pump inhibition', 'Caution in severe hepatic impairment'],
  ARRAY['Headache', 'Diarrhea', 'Nausea', 'Abdominal flatulence', 'Constipation'],
  ARRAY['Hypomagnesemia (with long-term use)', 'C. difficile-associated diarrhea', 'Interstitial nephritis', 'Osteoporotic fractures'],
  ARRAY['Take on an empty stomach 30-60 minutes before the morning meal'],
  ARRAY['Magnesium levels with prolonged therapy (>1 year); bone mineral density in high-risk patients'],
  'Category C / extensive epidemiological data show no increased risk of major malformations; use when clinically indicated.',
  'Compatible; excreted in breast milk in small amounts unlikely to harm infant.',
  'Approved for pediatric GERD and esophagitis (dosed 0.7-1 mg/kg/day).',
  'No dose adjustments required; use lowest effective maintenance dose.',
  'No dosage adjustment necessary in renal impairment.',
  'Dose reduction (max 20 mg/day) recommended in patients with severe hepatic impairment.',
  ARRAY['Profound acid suppression with proven ulcer healing rates', 'Once-daily morning dosing'],
  ARRAY['Inhibits CYP2C19; may decrease activation of clopidogrel and clearance of diazepam/phenytoin'],
  ARRAY['Must be taken 30-60 minutes before breakfast because active pumps are newly synthesized upon morning feeding'],
  'OmePRAZOLE = Pump Razor (Cuts proton pump) 30 min before breakfast.',
  '-prazole',
  'verified',
  'Indian Pharmacopoeia & KD Tripathi',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000009',
  'Pantoprazole',
  'Pantoprazole Sodium',
  'Pantoprazole',
  '6-(difluoromethoxy)-2-[(3,4-dimethoxypyridin-2-yl)methylsulfinyl]-1H-benzimidazole',
  'Substituted benzimidazole PPI with higher pH selectivity and lower CYP2C19 interaction potential than omeprazole.',
  '40 mg',
  ARRAY['Tablet (Enteric-coated)', 'IV Injection / Infusion'],
  ARRAY['Oral', 'Intravenous'],
  'Accumulates in parietal cell secretory canaliculi and converts at acidic pH to active sulfenamide, irreversibly inhibiting the H+/K+ ATPase enzyme.',
  'Suppresses basal and stimulated gastric acid output; neutralizes pH to facilitate ulcer healing and hemostasis in upper GI bleeding.',
  'Well absorbed following oral administration of enteric-coated tablets.',
  'Distributed into extracellular fluid.',
  'Extensively metabolized in the liver, primarily via CYP2C19 demethylation followed by sulfation; lower affinity for CYP2C19 than omeprazole.',
  'Renal (~80% as metabolites) and biliary (~20%).',
  '~77%',
  '1 to 1.5 hours (action lasts >24 hours)',
  '98%',
  '~0.15 L/kg',
  '~0.1 L/h/kg',
  '1 to 2 hours',
  '24 hours',
  ARRAY['Gastroesophageal reflux disease (GERD)', 'Erosive esophagitis', 'Gastric and duodenal ulcers', 'Prevention of NSAID-induced ulcers', 'Upper GI bleeding (IV infusion adjunctive to endoscopy)'],
  ARRAY['Hypersensitivity to pantoprazole or benzimidazole derivatives'],
  ARRAY['Prolonged acid suppression risks (hypomagnesemia, B12 deficiency, bone fractures with multi-year use)'],
  ARRAY['Administer 30-60 minutes before meals', 'Do not crush or chew enteric-coated tablets'],
  ARRAY['Headache', 'Diarrhea', 'Nausea', 'Abdominal pain', 'Dizziness'],
  ARRAY['Acute interstitial nephritis', 'Severe cutaneous adverse reactions (SCAR)', 'Hypomagnesemia', 'C. difficile colitis'],
  ARRAY['Take before breakfast; IV injection can be given regardless of food intake'],
  ARRAY['Magnesium levels and renal function in long-term therapy'],
  'Category B / preferred PPI in pregnancy when clinically needed.',
  'Excreted in low levels in human milk; compatible with breastfeeding.',
  'Safety and efficacy established for erosive esophagitis in children >= 5 years.',
  'No dose adjustments required in elderly patients.',
  'No dose adjustment necessary in renal failure or hemodialysis.',
  'No adjustment needed for mild to moderate hepatic impairment; monitor in severe cirrhosis.',
  ARRAY['Lower potential for CYP2C19-mediated drug-drug interactions (e.g. safer with clopidogrel than omeprazole)', 'Reliable IV formulation for hospital GI bleeds'],
  ARRAY['Requires acid activation; ineffective if given simultaneously with H2 blockers or antacids that raise pH before activation'],
  ARRAY['Preferred PPI in cardiac patients receiving clopidogrel due to minimal CYP2C19 competition'],
  'PANTO = Pure Acid Neutralization, Tolerable with Clopidogrel.',
  '-prazole',
  'verified',
  'Indian Pharmacopoeia & CDSCO',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000010',
  'Ondansetron',
  'Ondansetron Hydrochloride',
  'Ondansetron',
  '(3R)-9-methyl-3-[(2-methyl-1H-imidazol-1-yl)methyl]-2,3-dihydro-1H-carbazol-4-one',
  'Selective 5-HT3 receptor antagonist antiemetic widely used for chemotherapy, radiation, and post-operative nausea and vomiting.',
  '4 mg, 8 mg',
  ARRAY['Tablet', 'Orally Disintegrating Tablet (ODT)', 'Syrup', 'IV/IM Injection'],
  ARRAY['Oral', 'Intravenous', 'Intramuscular'],
  'Selectively and competitively blocks serotonin 5-HT3 receptors both peripherally on vagal nerve terminals in the gut and centrally in the chemoreceptor trigger zone (CTZ).',
  'Suppresses the emetic reflex cascade triggered by cytotoxic agents, gastrointestinal surgery, or acute gastroenteritis.',
  'Rapidly and completely absorbed from the GI tract; undergoes moderate first-pass metabolism.',
  'Moderately distributed into body tissues.',
  'Extensively metabolized in the liver via multiple cytochrome P450 pathways (CYP3A4, CYP1A2, CYP2D6).',
  'Renal (<5-10% as unchanged drug; balance as hepatic metabolites in urine and feces).',
  '~60%',
  '3 to 4 hours',
  '70-76%',
  '~1.9 L/kg',
  '~0.35 L/h/kg',
  '15 to 30 minutes',
  '4 to 8 hours',
  ARRAY['Chemotherapy-induced nausea and vomiting (CINV)', 'Radiotherapy-induced nausea and vomiting', 'Post-operative nausea and vomiting (PONV)', 'Acute gastroenteritis vomiting in emergency settings'],
  ARRAY['Concomitant use with apomorphine (profound hypotension and loss of consciousness)', 'Congenital long QT syndrome'],
  ARRAY['Dose-dependent QT interval prolongation; caution in patients with underlying cardiac conduction abnormalities or electrolyte imbalances (hypokalemia, hypomagnesemia)'],
  ARRAY['May cause constipation due to slowing of colonic transit'],
  ARRAY['Headache (most common)', 'Constipation', 'Flushing / sensation of warmth', 'Drowsiness'],
  ARRAY['QT prolongation / Torsades de Pointes', 'Serotonin syndrome (when combined with other serotonergic agents)', 'Severe hypersensitivity reactions'],
  ARRAY['Can be taken without regard to meals; Orally Disintegrating Tablets (ODT) placed on tongue dissolve rapidly'],
  ARRAY['ECG in patients with cardiac risk factors; serum potassium and magnesium'],
  'Category B / commonly prescribed for hyperemesis gravidarum under specialist guidance.',
  'Compatible; excreted in breast milk in small amounts.',
  'Widely used in pediatric acute gastroenteritis and oncology (dosed 0.15 mg/kg or by body surface area).',
  'No dose adjustments necessary in elderly.',
  'No dose adjustment necessary in renal impairment.',
  'Max dose 8 mg/day in severe hepatic impairment (Child-Pugh score >= 10).',
  'ARRAY['Highly effective for peripheral vagal and central emesis', 'Does not cause extrapyramidal side effects (unlike metoclopramide)'],
  ARRAY['Commonly causes headache and constipation; dose-dependent QT prolongation'],
  ARRAY['Drug of choice when extrapyramidal side effects of dopamine antagonists must be avoided'],
  'ONDAN = Out with Nausea, Direct Antagonist of 5-HT3.',
  '-setron',
  'verified',
  'Indian Pharmacopoeia & WHO NLEM',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000011',
  'Cetirizine',
  'Cetirizine Hydrochloride',
  'Cetirizine',
  '2-[2-[4-[(4-chlorophenyl)-phenylmethyl]piperazin-1-yl]ethoxy]acetic acid',
  'Second-generation selective H1 antihistamine with rapid onset and minimal central sedation.',
  '10 mg',
  ARRAY['Tablet', 'Syrup'],
  ARRAY['Oral'],
  'Competitively and selectively antagonizes peripheral histamine H1 receptors; also inhibits histamine release and eosinophil chemotaxis during the late-phase allergic response.',
  'Alleviates pruritus, rhinorrhea, sneezing, conjunctival injection, and urticarial wheals.',
  'Rapidly absorbed from the GI tract (peak plasma concentration achieved in ~1 hour).',
  'Low volume of distribution; poor penetration across the blood-brain barrier.',
  'Minimal hepatic metabolism via oxidative dealkylation (<10%).',
  'Predominantly renal excretion (70% unchanged in urine); 10% in feces.',
  '~70%',
  '7 to 10 hours (longer in renal impairment and elderly)',
  '93%',
  '~0.5 L/kg',
  '~0.6 mL/min/kg',
  '20 to 60 minutes',
  '24 hours',
  ARRAY['Allergic rhinitis (seasonal and perennial)', 'Chronic idiopathic urticaria', 'Allergic conjunctivitis', 'Pruritus and atopic eczema flares'],
  ARRAY['Severe renal impairment (CrCl < 10 mL/min)', 'Hypersensitivity to cetirizine or hydroxyzine'],
  ARRAY['Mild drowsiness can occur in susceptible individuals; avoid driving or operating machinery until individual tolerance is established'],
  ARRAY['Dose reduction required in renal insufficiency', 'Avoid co-ingestion with CNS depressants and alcohol'],
  ARRAY['Mild sedation / somnolence (in ~10% of users)', 'Dry mouth', 'Fatigue', 'Headache', 'Pharyngitis'],
  ARRAY['Severe hypersensitivity reactions (rare)', 'Paradoxical CNS excitation / convulsions in overdose'],
  ARRAY['Food slightly delays peak absorption time but does not decrease total extent of absorption'],
  ARRAY['Renal function in elderly and patients with known renal disease'],
  'Category B / wide safety database; preferred antihistamine in pregnancy.',
  'Compatible; small amounts excreted in milk.',
  'Approved in children >= 6 months (dosed 2.5 mg once to twice daily based on age).',
  'Start with 5 mg once daily due to age-related decline in renal clearance.',
  'Dose reduction to 5 mg every other day or 5 mg daily if CrCl 10-30 mL/min; contraindicated if CrCl < 10 mL/min.',
  'No dose adjustment needed in pure hepatic impairment.',
  ARRAY['Fast onset of action (often within 20-30 minutes)', 'Once-daily dosing with excellent safety profile in pregnancy and pediatrics'],
  ARRAY['Slightly more sedating than fexofenadine or loratadine in a minority of patients'],
  ARRAY['Active carboxylic acid metabolite of hydroxyzine; does not significantly cross the blood-brain barrier'],
  'CET = Clean Elimination via kidney, Ten mg Once a day.',
  '-irizine',
  'verified',
  'Indian Pharmacopoeia & CDSCO',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000012',
  'Salbutamol',
  'Salbutamol (Albuterol) Sulphate',
  'Salbutamol',
  '4-[2-(tert-butylamino)-1-hydroxyethyl]-2-(hydroxymethyl)phenol',
  'Short-acting selective beta-2 adrenergic agonist (SABA) serving as the frontline rescue bronchodilator in asthma and COPD.',
  '100 mcg/puff MDI, 2 mg, 4 mg, 2.5 mg/2.5 mL Respule',
  ARRAY['Metered Dose Inhaler (MDI)', 'Dry Powder Inhaler (DPI)', 'Nebulizer Solution', 'Tablet', 'Syrup'],
  ARRAY['Inhalation', 'Oral'],
  'Stimulates beta-2 adrenergic receptors on airway smooth muscle, activating adenylate cyclase, increasing intracellular cAMP, and causing bronchial relaxation.',
  'Rapid relief of acute bronchospasm; inhibits mediator release from mast cells and enhances mucociliary clearance.',
  'Inhaled fraction acts directly on bronchiolar smooth muscle; swallowed fraction undergoes first-pass hepatic metabolism.',
  'Rapid local airway distribution; low systemic concentrations after inhalation.',
  'Hepatic sulfation to inactive 4-O-sulfate metabolite.',
  'Renal (~80% in urine as unchanged drug and sulfate conjugate within 24 hours).',
  'Inhaled: 10-20% lung deposition; Oral: ~50%',
  '3.8 to 6 hours',
  '~10%',
  '~150 L',
  '~30 L/h',
  '5 to 15 minutes (inhalation); 30 minutes (oral)',
  '3 to 6 hours',
  ARRAY['Acute bronchospasm in bronchial asthma', 'Chronic Obstructive Pulmonary Disease (COPD)', 'Exercise-induced bronchospasm prophylaxis', 'Hyperkalemia emergency management (adjunctive IV/nebulized therapy)'],
  ARRAY['Hypersensitivity to salbutamol', 'Non-IV formulations for threatened abortion'],
  ARRAY['Overuse (>2 canisters/month) indicates poorly controlled asthma and correlates with increased mortality; must step up controller inhaled corticosteroids (ICS)'],
  ARRAY['Cardiovascular disorders (arrhythmias, hypertension)', 'Diabetes mellitus (risk of ketoacidosis with high parenteral doses)', 'Hypokalemia risk with high doses'],
  ARRAY['Fine skeletal muscle tremor (especially hands)', 'Palpitations', 'Tachycardia', 'Headache', 'Nervousness'],
  ARRAY['Paradoxical bronchospasm', 'Hypokalemia', 'Cardiac arrhythmias (supraventricular tachycardia, atrial fibrillation)'],
  ARRAY['None significant for inhaled formulation'],
  ARRAY['Peak Expiratory Flow Rate (PEFR)', 'Frequency of rescue inhaler use per week', 'Serum potassium with high-dose nebulized therapy'],
  'Category C / safe and standard rescue bronchodilator across all trimesters of pregnancy.',
  'Compatible; inhaled route yields negligible maternal systemic levels.',
  'Standard rescue inhaler for pediatric asthma (1-2 puffs via spacer with mask).',
  'Monitor heart rate and potential exacerbation of underlying ischemic heart disease.',
  'No dose adjustments for inhaled formulation.',
  'No dose adjustments needed.',
  ARRAY['Gold standard rapid rescue bronchodilator', 'Minimal systemic toxicity when administered via inhaler with proper spacer technique'],
  ARRAY['Short duration requires frequent administration if asthma is uncontrolled', 'Tremor and tachycardia at higher doses'],
  ARRAY['Always use a spacer device with MDIs for optimal lung deposition and reduced oral impaction'],
  'SAL = Smooth Airway Lumens; Beta-2 Bronchodilation.',
  '-terol',
  'verified',
  'Indian Pharmacopoeia & GINA Guidelines',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000013',
  'Metformin',
  'Metformin Hydrochloride',
  'Metformin',
  '1,1-dimethylbiguanide hydrochloride',
  'First-line oral biguanide antihyperglycemic agent for type 2 diabetes mellitus with proven cardiovascular safety.',
  '500 mg, 850 mg, 1000 mg, 500 mg SR',
  ARRAY['Tablet (Immediate Release)', 'Tablet (Sustained/Extended Release)'],
  ARRAY['Oral'],
  'Activates AMP-activated protein kinase (AMPK), inhibiting hepatic gluconeogenesis and glycogenolysis, enhancing peripheral insulin sensitivity, and slowing intestinal glucose absorption.',
  'Lowers both basal and postprandial plasma glucose without stimulating insulin secretion (euglycemic agent; does not cause hypoglycemia as monotherapy).',
  'Slowly and incompletely absorbed from the small intestine (bioavailability ~50-60%).',
  'Negligible plasma protein binding; distributes into erythrocytes and gastrointestinal tissue.',
  'Not metabolized by the liver; excreted completely unchanged.',
  'Renal elimination via active tubular secretion (OCT2) and glomerular filtration.',
  '~50-60%',
  '4 to 6.5 hours (plasma); ~17 hours (erythrocytes)',
  '<5% (negligible)',
  '~654 L',
  '~450-550 mL/min',
  '1 to 2 hours (clinical glucose lowering builds over 1-2 weeks)',
  '8 to 12 hours (extended release provides 24-hour coverage)',
  ARRAY['Type 2 Diabetes Mellitus (first-line monotherapy and combination)', 'Polycystic Ovary Syndrome (PCOS)', 'Prediabetes in high-risk individuals'],
  ARRAY['Severe renal impairment (eGFR < 30 mL/min/1.73 m²)', 'Acute or chronic metabolic acidosis (including diabetic ketoacidosis)', 'Severe tissue hypoxia (acute heart failure, shock, sepsis)'],
  ARRAY['Lactic acidosis is a rare but life-threatening complication, almost exclusively seen in severe renal or cardiorespiratory failure', 'Hold 48 hours before iodinated contrast procedures'],
  ARRAY['Dose titration in 500mg increments with meals reduces GI intolerance', 'Monitor for vitamin B12 deficiency in long-term therapy'],
  ARRAY['Diarrhea', 'Nausea', 'Abdominal bloating', 'Metallic taste in mouth', 'Flatulence'],
  ARRAY['Lactic acidosis (rare: ~3 cases per 100,000 patient-years)', 'Macrocytic anemia due to B12 malabsorption'],
  ARRAY['Take with or immediately after meals to minimize gastrointestinal discomfort'],
  ARRAY['eGFR baseline and annually (every 3-6 months if eGFR 30-59)', 'Serum Vitamin B12 levels every 2-3 years', 'HbA1c every 3 months'],
  'Category B / widely used with strong safety data in gestational diabetes and PCOS.',
  'Compatible; excreted in breast milk in small amounts without recorded adverse effects.',
  'Approved in children >= 10 years for Type 2 Diabetes.',
  'Use cautiously due to higher prevalence of occult renal impairment; monitor eGFR regularly.',
  'eGFR 45-59: Max 2000 mg/day; eGFR 30-44: Max 1000 mg/day; eGFR < 30: Contraindicated.',
  'Avoid in severe liver disease or cirrhosis due to impaired lactic acid clearance.',
  ARRAY['Weight neutral or promotes mild weight loss', 'Zero inherent hypoglycemia risk when used as monotherapy', 'Long-term cardiovascular protection'],
  ARRAY['Gastrointestinal side effects are frequent during initiation', 'Contraindicated in advanced renal impairment'],
  ARRAY['Sustained Release (SR/ER) formulations taken with the evening meal drastically reduce gastrointestinal symptoms'],
  'MET = Makes Extra Toxicity (Lactate) if eGFR < 30; First-line Metabolic Miracle.',
  '-formin',
  'verified',
  'Indian Pharmacopoeia & ICMR Diabetes Guidelines',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000014',
  'Amlodipine',
  'Amlodipine Besylate',
  'Amlodipine',
  '3-ethyl-5-methyl 2-(2-aminoethoxymethyl)-4-(2-chlorophenyl)-6-methyl-1,4-dihydropyridine-3,5-dicarboxylate',
  'Third-generation dihydropyridine calcium channel blocker (CCB) with gradual onset and long 24-hour smooth action.',
  '2.5 mg, 5 mg, 10 mg',
  ARRAY['Tablet'],
  ARRAY['Oral'],
  'Inhibits transmembrane influx of extracellular calcium ions into vascular smooth muscle and cardiac muscle through L-type voltage-gated calcium channels.',
  'Causes peripheral arterial vasodilation, reducing total peripheral resistance, afterload, and systemic blood pressure; also dilates coronary arteries.',
  'Slowly and almost completely absorbed from the gastrointestinal tract.',
  'Large volume of distribution with extensive tissue binding.',
  'Extensively metabolized in the liver (90%) via CYP3A4 to inactive pyridine metabolites.',
  'Renal (10% unchanged, 60% as metabolites); 20-25% biliary/fecal.',
  '~64-90%',
  '35 to 50 hours (prolonged half-life allows steady once-daily BP control)',
  '97.5%',
  '~21 L/kg',
  '~7 mL/min/kg',
  '6 to 12 hours (steady-state reached in 7-8 days)',
  '24 to 36 hours',
  ARRAY['Essential hypertension', 'Chronic stable angina pectoris', 'Vasospastic (Prinzmetal) angina', 'Coronary artery disease'],
  ARRAY['Severe hypotension', 'Cardiogenic shock', 'Severe aortic stenosis', 'Hypersensitivity to dihydropyridines'],
  ARRAY['Peripheral pedal edema is dose-dependent and caused by precapillary arteriolar dilation (not fluid overload)'],
  ARRAY['Start with 2.5 mg in elderly or severe hepatic impairment', 'May interact with CYP3A4 inhibitors (clarithromycin, ketoconazole)'],
  ARRAY['Peripheral ankle edema (dose-dependent)', 'Flushing', 'Dizziness', 'Headache', 'Palpitations', 'Fatigue'],
  ARRAY['Severe hypotension / syncope', 'Worsening angina upon initiation (rare)', 'Gingival hyperplasia (rare)'],
  ARRAY['Can be taken with or without food; avoid excessive grapefruit juice (inhibits CYP3A4)'],
  ARRAY['Blood pressure', 'Heart rate', 'Inspection of lower extremities for bilateral ankle edema'],
  'Category C / use during pregnancy only if benefit justifies potential fetal risk (Labetalol / Nifedipine preferred).',
  'Excreted into human breast milk; monitor nursing infant.',
  'Approved in children >= 6 years for hypertension (dosed 2.5-5 mg once daily).',
  'Start at 2.5 mg once daily due to decreased clearance and prolonged half-life.',
  'No dosage adjustment required in renal impairment or dialysis.',
  'Start at 2.5 mg once daily due to extensive hepatic metabolism and clearance reduction.',
  ARRAY['Long 35-50h half-life provides seamless 24h BP control even with delayed/missed doses', 'Does not suppress cardiac conduction/contractility like verapamil'],
  ARRAY['Dose-dependent dependent edema is common at 10 mg dose (often combined with ARB/ACEi to counter edema)'],
  ARRAY['Pedal edema with amlodipine is vasodilatory, so diuretics are ineffective; adding an ARB/ACEi reverses arteriolar pooling'],
  'AMLO = Ankle edema, Morning dose, Long Acting (35-50h half-life).',
  '-dipine',
  'verified',
  'Indian Pharmacopoeia & Indian Guidelines on Hypertension',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000015',
  'Losartan',
  'Losartan Potassium',
  'Losartan',
  '[2-butyl-5-chloro-3-[[4-[2-(2H-tetrazol-5-yl)phenyl]phenyl]methyl]imidazol-4-yl]methanol',
  'Prototype Angiotensin II receptor blocker (ARB) offering blood pressure reduction and renal protection without bradykinin cough.',
  '25 mg, 50 mg, 100 mg',
  ARRAY['Tablet'],
  ARRAY['Oral'],
  'Competitively blocks the AT1 subtype receptor for angiotensin II in vascular smooth muscle and adrenal cortex; active metabolite E-3174 is 10-40x more potent.',
  'Blocks angiotensin II vasoconstriction and aldosterone secretion; produces mild uricosuric action by inhibiting renal URAT1 transporter.',
  'Well absorbed but undergoes substantial first-pass hepatic metabolism.',
  'Does not cross blood-brain barrier significantly.',
  'Hepatic oxidation via CYP2C9 and CYP3A4 to active carboxylic acid metabolite (EXP-3174).',
  'Biliary (60%) and renal (35% in urine as unchanged parent and active metabolite).',
  '~33%',
  'Losartan: 2 hours; Active metabolite E-3174: 6 to 9 hours',
  '~98.7%',
  '~34 L',
  '~600 mL/min (Losartan); ~50 mL/min (E-3174)',
  '1 hour (peak BP effect in 3 to 6 hours)',
  '24 hours',
  ARRAY['Essential hypertension', 'Diabetic nephropathy in Type 2 diabetes with elevated serum creatinine and proteinuria', 'Stroke risk reduction in hypertensive patients with LVH'],
  ARRAY['Pregnancy (fetal toxicity/death in 2nd and 3rd trimesters)', 'Concomitant aliskiren in patients with diabetes mellitus', 'Severe hepatic impairment'],
  ARRAY['Fetal toxicity: Discontinue immediately if pregnancy is detected', 'Hyperkalemia risk when co-administered with potassium supplements or spironolactone'],
  ARRAY['Bilateral renal artery stenosis (risk of acute renal failure)', 'Volume- or salt-depleted patients'],
  ARRAY['Dizziness', 'Hyperkalemia', 'Hypotension', 'Fatigue', 'Upper respiratory congestion'],
  ARRAY['Angioedema (much lower incidence than ACE inhibitors)', 'Acute kidney injury in bilateral renal artery stenosis', 'Severe hyperkalemia'],
  ARRAY['Can be taken with or without meals; avoid potassium-containing salt substitutes'],
  ARRAY['Serum potassium and serum creatinine at baseline and 2-4 weeks after initiation'],
  'Category D / Contraindicated in pregnancy (causes fetal renal agenesis, oligohydramnios, skull hypoplasia).',
  'Avoid during breastfeeding; alternative antihypertensives preferred.',
  'Approved in children >= 6 years (dosed 0.7 mg/kg once daily, max 50 mg).',
  'Standard initial dose 25-50 mg; monitor renal function and potassium.',
  'No starting dose adjustment necessary unless volume depleted.',
  'Consider lower starting dose of 25 mg in mild to moderate hepatic impairment; contraindicated in severe cirrhosis.',
  ARRAY['No bradykinin accumulation (does not cause ACE-inhibitor dry cough)', 'Unique uricosuric property beneficial in hypertensive patients with gout'],
  ARRAY['Absolute contraindication in pregnancy', 'Risk of hyperkalemia requiring potassium monitoring'],
  ARRAY['Unlike other ARBs, Losartan uniquely lowers serum uric acid levels by blocking the URAT1 renal transporter'],
  'SARTAN = Blocks AT1 Receptor, Totally Avoid in Pregnancy.',
  '-sartan',
  'verified',
  'Indian Pharmacopoeia & KD Tripathi',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000016',
  'Telmisartan',
  'Telmisartan',
  'Telmisartan',
  '2-[4-[[4-methyl-6-(1-methylbenzimidazol-2-yl)-2-propylbenzimidazol-1-yl]methyl]phenyl]benzoic acid',
  'Longest-acting ARB with highest AT1 affinity and partial PPAR-gamma agonism for metabolic and cardiovascular protection.',
  '20 mg, 40 mg, 80 mg',
  ARRAY['Tablet'],
  ARRAY['Oral'],
  'Insurmountable selective blockade of the AT1 receptor with dissociation half-life of several hours; also functions as a partial agonist of PPAR-gamma.',
  'Reduces systemic vascular resistance and blood pressure; improves insulin sensitivity and lipid metabolism through PPAR-gamma activation.',
  'Rapidly absorbed; bioavailability is dose-dependent (42% at 40 mg, 58% at 160 mg).',
  'Highly lipophilic; large volume of distribution and high tissue penetration.',
  'Hepatic glucuronidation to inactive 1-O-acylglucuronide (no CYP enzyme involvement).',
  'Almost exclusively fecal/biliary excretion (>98%); <1% excreted in urine.',
  '~42-58%',
  '~24 hours (longest elimination half-life of all ARBs)',
  '>99.5%',
  '~500 L',
  '~800 mL/min',
  '1 to 2 hours',
  '24+ hours (smooth 24-hour BP control including morning surge)',
  ARRAY['Essential hypertension', 'Cardiovascular risk reduction in patients aged >= 55 with coronary, peripheral, or cerebrovascular disease unable to take ACE inhibitors'],
  ARRAY['Pregnancy (2nd and 3rd trimesters)', 'Biliary obstructive disorders / severe hepatic impairment', 'Concomitant aliskiren in diabetics'],
  ARRAY['Discontinue immediately upon pregnancy confirmation', 'Hyperkalemia risk in combination with potassium-sparing diuretics'],
  ARRAY['Renal artery stenosis', 'Volume depletion', 'Severe obstructive biliary disease'],
  ARRAY['Dizziness', 'Sinusitis / back pain', 'Diarrhea', 'Hyperkalemia', 'Hypotension'],
  ARRAY['Angioedema', 'Acute renal insufficiency', 'Severe hyperkalemia'],
  ARRAY['Can be taken with or without food; store in original blister pack (hygroscopic)'],
  ARRAY['Blood pressure (specifically morning surge)', 'Serum creatinine and potassium'],
  'Category D / Contraindicated throughout pregnancy.',
  'Not recommended during breastfeeding; long half-life and lipophilicity.',
  'Safety and effectiveness in pediatric patients not established.',
  'No initial dose adjustment required in elderly.',
  'Safe in severe renal impairment and hemodialysis without dose adjustment (due to >98% biliary excretion).',
  'Initial dose 20 mg once daily in mild to moderate hepatic impairment; contraindicated in severe biliary obstruction.',
  ARRAY['True 24-hour blood pressure control with protection against early morning cardiovascular events', 'Dual ARB + PPAR-gamma metabolic profile', 'Completely safe in renal failure due to pure biliary elimination'],
  ARRAY['Hygroscopic tablets degrade quickly if left exposed to ambient air outside blister'],
  ARRAY['Telmisartan is the only ARB with FDA/international indication for cardiovascular risk reduction equivalent to ramipril'],
  'TELMI = Twenty-four hour Elimination half-life + Lowers Morning surge.',
  '-sartan',
  'verified',
  'Indian Pharmacopoeia & ONTARGET Trial Data',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000017',
  'Atorvastatin',
  'Atorvastatin Calcium',
  'Atorvastatin',
  '(3R,5R)-7-[2-(4-fluorophenyl)-3-phenyl-4-(phenylcarbamoyl)-5-propan-2-ylpyrrol-1-yl]-3,5-dihydroxyheptanoic acid',
  'High-intensity synthetic statin offering potent LDL-C reduction and proven plaque stabilization in cardiovascular prevention.',
  '10 mg, 20 mg, 40 mg, 80 mg',
  ARRAY['Tablet'],
  ARRAY['Oral'],
  'Competitive inhibitor of 3-hydroxy-3-methylglutaryl-coenzyme A (HMG-CoA) reductase, the rate-limiting enzyme in cholesterol biosynthesis; upregulates hepatic LDL receptors.',
  'Dose-dependently lowers LDL-C (35-60%), triglycerides (20-40%), and apolipoprotein B; pleiotropic effects improve endothelial nitric oxide and reduce vascular inflammation.',
  'Rapidly absorbed (peak concentration in 1-2 hours); extensive first-pass metabolism.',
  'Widely distributed; does not cross blood-brain barrier significantly.',
  'Extensively metabolized in the liver via CYP3A4 to active ortho- and parahydroxylated metabolites (which account for 70% of circulating HMG-CoA reductase inhibitory activity).',
  'Biliary elimination (>98%); <2% excreted in urine.',
  '~14%',
  '14 hours (parent drug); 20 to 30 hours (active metabolites)',
  '>=98%',
  '~381 L',
  '~625 mL/min',
  '1 to 2 hours (therapeutic lipid reduction visible in 2-4 weeks)',
  '24 to 30 hours',
  ARRAY['Primary hyperlipidemia and mixed dyslipidemia', 'Primary prevention of cardiovascular disease in high-risk patients', 'Secondary prevention of acute coronary syndromes, MI, and stroke', 'Familial hypercholesterolemia'],
  ARRAY['Active liver disease or unexplained persistent elevations of serum transaminases', 'Pregnancy and lactation', 'Concomitant strong CYP3A4 inhibitors (clarithromycin, itraconazole) at high statin doses'],
  ARRAY['Risk of myopathy and rhabdomyolysis (warn patients to promptly report unexplained muscle pain or brown urine)', 'Small dose-dependent increase in HbA1c/fasting glucose'],
  ARRAY['Heavy alcohol consumption', 'History of liver disease', 'Check baseline lipid panel and liver enzymes'],
  ARRAY['Myalgia', 'Dyspepsia', 'Headache', 'Nasopharyngitis', 'Mild AST/ALT elevation', 'Constipation'],
  ARRAY['Rhabdomyolysis with acute kidney injury', 'Immune-mediated necrotizing myopathy (IMNM)', 'Severe hepatotoxicity'],
  ARRAY['Can be taken any time of day (unlike short-acting simvastatin which requires bedtime dosing); avoid large volumes of grapefruit juice (>1 L/day)'],
  ARRAY['Baseline lipid profile and ALT; repeat lipids at 4-12 weeks; check CK only if patient develops muscle pain/weakness'],
  'Category X / Contraindicated in pregnancy (cholesterol is essential for fetal organ development).',
  'Contraindicated during breastfeeding due to potential disruption of infant lipid metabolism.',
  'Approved in children >= 10 years with familial hypercholesterolemia.',
  'No dose adjustments needed solely based on age; monitor for muscle symptoms.',
  'No dosage adjustment required in renal disease or dialysis (biliary excretion).',
  'Contraindicated in active liver disease; use caution in chronic stable liver disease.',
  ARRAY['Can be administered at any time of day due to long-lived active metabolites', 'High intensity lipid lowering without dose adjustment in renal failure'],
  ARRAY['Subject to CYP3A4-mediated drug interactions', 'Contraindicated in pregnancy'],
  ARRAY['Does not require evening/bedtime dosing unlike short-acting statins (pravastatin, simvastatin)'],
  'STATIN = Stop Transaminases rising + Take Any Time + Inhibits Next-MI.',
  '-statin',
  'verified',
  'Indian Pharmacopoeia & Lipid Association of India (LAI)',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000018',
  'Aspirin',
  'Aspirin (Acetylsalicylic Acid)',
  'Aspirin',
  '2-acetoxybenzoic acid',
  'Irreversible platelet cyclooxygenase-1 inhibitor used as the foundational antiplatelet agent in ischemic vascular disease.',
  '75 mg, 150 mg, 325 mg',
  ARRAY['Enteric-coated Tablet', 'Dispersible Tablet', 'Chewable Tablet'],
  ARRAY['Oral'],
  'Irreversibly acetylates Serine-529 of cyclooxygenase-1 (COX-1), blocking platelet synthesis of Thromboxane A2 (TXA2) for the entire 7-10 day lifespan of the platelet.',
  'Inhibits platelet aggregation, clot formation, and arterial thrombus propagation.',
  'Rapidly absorbed from stomach and upper small intestine; unacetylated salicylate hydrolyzed in gut and liver.',
  'Widely distributed to all body tissues; crosses placenta and blood-brain barrier.',
  'Rapidly hydrolyzed in liver and plasma by esterases to salicylic acid, then conjugated with glycine to salicyluric acid.',
  'Renal excretion of salicylic acid is pH-dependent (alkalinization increases excretion markedly).',
  '~50-70% (due to rapid hydrolysis)',
  'Aspirin: 15 to 20 minutes; Salicylate: 2 to 3 hours (low dose)',
  '80-90% (salicylate bound to albumin)',
  '~0.15 L/kg',
  '~9.3 mL/min/kg',
  'Chewable: 15 to 30 minutes; Enteric coated: 2 to 4 hours',
  '7 to 10 days (irreversible platelet inactivation persists for entire platelet lifespan)',
  ARRAY['Secondary prevention of myocardial infarction and stroke', 'Acute Coronary Syndrome (loading dose 150-325 mg chewable)', 'Post-PCI stent thrombosis prevention', 'Ischemic stroke / TIA prevention', 'Colorectal cancer chemoprevention in selected populations'],
  ARRAY['Active peptic ulcer disease', 'History of aspirin-induced asthma / triad (nasal polyps, asthma, NSAID sensitivity)', 'Bleeding disorders / Hemophilia', 'Children and adolescents with viral illness (Reye syndrome risk)'],
  ARRAY['GI bleeding risk increases with age and concomitant anticoagulants/NSAIDs', 'Discontinue 5-7 days before major elective surgery if bleeding risk outweighs thrombotic risk'],
  ARRAY['Concurrent use with ibuprofen may compete with aspirin binding site on COX-1 (take aspirin 30 min before ibuprofen)', 'Pre-existing asthma'],
  ARRAY['Dyspepsia', 'Heartburn', 'Epigastric discomfort', 'Easy bruising', 'Bleeding time prolongation'],
  ARRAY['Major GI hemorrhage', 'Hemorrhagic stroke', 'Aspirin-exacerbated respiratory disease (AERD)', 'Reye syndrome in children'],
  ARRAY['Take with food to minimize gastric irritation; in acute chest pain, chew non-enteric tablet for rapid absorption'],
  ARRAY['Hemoglobin/Hematocrit in patients with anemia symptoms; stool occult blood if GI bleeding suspected'],
  'Avoid in third trimester (premature ductus arteriosus closure and maternal/fetal bleeding). Low-dose (75-150 mg) is used under specialist care for pre-eclampsia prevention.',
  'Avoid high doses; low-dose antiplatelet is compatible with close monitoring.',
  'Contraindicated in children < 16 years with viral fever due to risk of fatal Reye syndrome.',
  'High risk of gastrointestinal bleeding; use co-prescribed PPI in high-risk patients.',
  'Caution in severe renal impairment; risk of fluid retention and deterioration of renal function.',
  'Avoid in severe hepatic impairment due to coagulopathy.',
  ARRAY['Inexpensive, robustly proven mortality reduction in secondary cardiovascular prevention', 'Rapid antiplatelet effect within minutes of chewing'],
  ARRAY['Irreversible antiplatelet effect cannot be rapidly reversed (requires new platelet turnover or transfusion)', 'Ulcerogenic potential'],
  ARRAY['In suspected acute heart attack, CHEW a 150-325 mg uncoated or dispersible tablet immediately for rapid buccal and gastric absorption'],
  'ASPIRIN = Antiplatelet, Salicylate, Prevents Infarction, Reye syndrome in kids (Avoid).',
  '-aspirin',
  'verified',
  'Indian Pharmacopoeia & Cardiology Society of India (CSI)',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000019',
  'Clopidogrel',
  'Clopidogrel Bisulphate',
  'Clopidogrel',
  'methyl (2S)-2-(2-chlorophenyl)-2-(6,7-dihydro-4H-thieno[3,2-c]pyridin-5-yl)acetate',
  'Thienopyridine prodrug antiplatelet agent that irreversibly blocks platelet P2Y12 ADP receptors.',
  '75 mg, 300 mg (loading)',
  ARRAY['Tablet'],
  ARRAY['Oral'],
  'Hepatically bioactivated prodrug; active thiol metabolite irreversibly binds to and antagonizes platelet P2Y12 adenosine diphosphate (ADP) receptors, preventing GPIIb/IIIa complex activation.',
  'Inhibits ADP-induced platelet activation and aggregation for the lifespan of the platelet.',
  'Well absorbed (>50%); 85% of circulating drug is hydrolyzed by esterases to inactive carboxylic acid derivative.',
  'Moderate volume of distribution.',
  'Hepatic two-step CYP450 bioactivation (CYP2C19, CYP3A4, CYP1A2, CYP2B6) generating the active thiol metabolite (~15% of dose).',
  '50% renal and 46% fecal over a 5-day period.',
  '~50%',
  'Parent drug: 6 hours; Active metabolite: ~30 minutes',
  '98% (parent drug)',
  '~2.5 L/kg',
  '~18 L/h',
  '2 hours (with 300-600 mg loading dose); 3-7 days with 75 mg daily maintenance',
  '7 to 10 days (irreversible platelet inhibition)',
  ARRAY['Acute Coronary Syndrome (NSTEMI, STEMI, Unstable Angina) in Dual Antiplatelet Therapy (DAPT)', 'Recent myocardial infarction or ischemic stroke', 'Established peripheral arterial disease', 'Post-coronary stenting (PCI)'],
  ARRAY['Active pathological bleeding (peptic ulcer or intracranial hemorrhage)', 'Severe hepatic impairment', 'Hypersensitivity to clopidogrel'],
  ARRAY['Diminished antiplatelet effect in CYP2C19 poor metabolizers (*2/*3 alleles); alternative P2Y12 inhibitors (ticagrelor/prasugrel) or CYP testing recommended in high-risk PCI'],
  ARRAY['Avoid co-administration with strong CYP2C19 inhibitors like omeprazole (use pantoprazole instead)', 'Discontinue 5-7 days before elective CABG/surgery'],
  ARRAY['Bleeding / bruising', 'Dyspepsia', 'Diarrhea', 'Abdominal pain', 'Rash'],
  ARRAY['Major bleeding (GI, intracranial)', 'Thrombotic Thrombocytopenic Purpura (TTP - rare but urgent)', 'Agranulocytosis / Aplastic anemia'],
  ARRAY['Can be taken with or without food; take pantoprazole rather than omeprazole if PPI gastroprotection is required'],
  ARRAY['Complete Blood Count (CBC) and platelet count; monitor for signs of occult bleeding'],
  'Category B / use only if clearly needed (e.g. coronary stenting during pregnancy).',
  'Avoid during breastfeeding; safety not established in human milk.',
  'Safety and efficacy not established in pediatric patients.',
  'No dose adjustment required for elderly patients.',
  'No dosage adjustment required in mild-moderate renal impairment; monitor for bleeding.',
  'Use with caution in moderate hepatic impairment; contraindicated in severe liver failure.',
  ARRAY['Synergistic with aspirin in Dual Antiplatelet Therapy (DAPT) post-stenting', 'Alternative for patients with true aspirin allergy'],
  ARRAY['Requires two-step hepatic CYP2C19 activation; vulnerable to genetic polymorphism non-responsiveness and drug interactions'],
  ARRAY['When co-prescribing a PPI with clopidogrel, choose Pantoprazole over Omeprazole to prevent CYP2C19 competition'],
  'CLOP = Clot Lessening On Platelets; 2C19 Dependent.',
  '-grel',
  'verified',
  'Indian Pharmacopoeia & ACC/AHA Guidelines',
  '2026-08-01',
  '1.0'
),
(
  '44444444-0000-0000-0000-000000000020',
  'Levothyroxine',
  'Levothyroxine Sodium (T4)',
  'Levothyroxine',
  'sodium (2S)-2-amino-3-[4-(4-hydroxy-3,5-diiodophenoxy)-3,5-diiodophenyl]propanoate',
  'Synthetic crystalline levorotatory isomer of thyroxine (T4) for replacement therapy in hypothyroidism.',
  '12.5 mcg, 25 mcg, 50 mcg, 75 mcg, 88 mcg, 100 mcg, 112 mcg, 125 mcg, 150 mcg',
  ARRAY['Tablet'],
  ARRAY['Oral', 'IV Injection (for Myxedema Coma)'],
  'Synthetic T4 converted in peripheral tissues by 5''-deiodinase enzymes to active triiodothyronine (T3), which enters cell nuclei and binds to thyroid hormone receptors, regulating protein synthesis and metabolism.',
  'Normalizes basal metabolic rate, cardiac output, lipid clearance, mental alertness, and thermogenesis across all organ systems.',
  'Variable absorption (40-80%) predominantly in the jejunum and ileum; significantly impaired by food, calcium, iron, and coffee.',
  'Over 99% bound to thyroid-binding globulin (TBG), transthyretin, and albumin.',
  'Peripheral deiodination in liver and kidney to active T3 and reverse T3; hepatic glucuronidation.',
  'Renal (~80%) and fecal/biliary (~20%).',
  '~60-80%',
  '6 to 7 days (euthyroid); 9 to 10 days (hypothyroid); 3 to 4 days (hyperthyroid)',
  '>99.9% (very high protein binding)',
  '~11 to 15 L',
  '~0.05 L/h',
  '3 to 5 days (clinical symptom improvement takes 2 to 4 weeks; full steady-state at 6-8 weeks)',
  'Several days to 1-2 weeks after discontinuation due to 7-day half-life',
  ARRAY['Primary, secondary, and tertiary hypothyroidism', 'Congenital hypothyroidism (Cretinism)', 'TSH suppression in thyroid nodules and differentiated thyroid cancer', 'Myxedema coma'],
  ARRAY['Untreated subclinical or overt thyrotoxicosis', 'Acute myocardial infarction', 'Untreated adrenal insufficiency (must replace cortisol first to avoid adrenal crisis)'],
  ARRAY['Narrow therapeutic index drug: over-replacement causes bone demineralization (osteopenia/osteoporosis) and cardiac arrhythmias (atrial fibrillation)', 'Do not use for weight loss'],
  ARRAY['Must be taken early morning on an empty stomach with plain water at least 30-60 minutes before tea, coffee, breakfast, or other medications'],
  ARRAY['Palpitations', 'Tachycardia', 'Tremors', 'Insomnia', 'Weight loss', 'Heat intolerance', 'Diarrhea', 'Anxiety (all signs of over-replacement)'],
  ARRAY['Atrial fibrillation / Supraventricular arrhythmias', 'Angina / Myocardial ischemia in elderly coronary patients', 'Osteoporosis (long-term oversuppression)'],
  ARRAY['Calcium, iron supplements, antacids, soy, coffee, and dietary fiber severely reduce absorption - separate by at least 4 hours'],
  ARRAY['Serum TSH every 6-8 weeks after any dose adjustment until euthyroid, then annually; free T4 in central hypothyroidism'],
  'Category A / absolutely safe and essential in pregnancy; maternal requirements typically increase by 30-50% in early gestation.',
  'Compatible; minimal amounts excreted in milk.',
  'Crucial in infants and children to prevent irreversible neurocognitive deficits (Cretinism); dosed by weight and age.',
  'Start low (12.5-25 mcg/day) and go slow in elderly patients with underlying coronary artery disease.',
  'No dose adjustments required.',
  'No dose adjustments required; monitor TSH.',
  ARRAY['Synthetic formulation identical to natural human thyroxine', 'Long 7-day half-life provides stable physiological levels without peak-trough fluctuations'],
  ARRAY['Narrow therapeutic index requiring strict adherence and periodic TSH laboratory monitoring', 'Easily bound/impaired by common foods and minerals'],
  ARRAY['Always instruct patients: Take first thing in the morning with plain water, wait 45 minutes before tea/coffee/food, and wait 4 hours before calcium or iron'],
  'LEVO = Low Energy Vanishes Once T4 Replaced; Take on Empty Stomach.',
  '-thyroxine',
  'verified',
  'Indian Pharmacopoeia & Indian Thyroid Society Guidelines',
  '2026-08-01',
  '1.0'
)
ON CONFLICT (id) DO NOTHING;

-- Brands Junction (Common Verified Indian Brands)
INSERT INTO public.brands (id, brand_name, medicine_id, manufacturer_id, strength, dosage_form, route, verified) VALUES
('55555555-0000-0000-0000-000000000001', 'Dolo-650', '44444444-0000-0000-0000-000000000001', '22222222-0000-0000-0000-000000000009', '650 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000002', 'Crocin 650', '44444444-0000-0000-0000-000000000001', '22222222-0000-0000-0000-000000000005', '650 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000003', 'Brufen 400', '44444444-0000-0000-0000-000000000002', '22222222-0000-0000-0000-000000000004', '400 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000004', 'Voveran 50', '44444444-0000-0000-0000-000000000003', '22222222-0000-0000-0000-000000000006', '50 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000005', 'Novamox 500', '44444444-0000-0000-0000-000000000004', '22222222-0000-0000-0000-000000000001', '500 mg', 'Capsule', 'Oral', true),
('55555555-0000-0000-0000-000000000006', 'Augmentin 625 Duo', '44444444-0000-0000-0000-000000000005', '22222222-0000-0000-0000-000000000005', '625 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000007', 'Azithral 500', '44444444-0000-0000-0000-000000000006', '22222222-0000-0000-0000-000000000007', '500 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000008', 'Doxicip 100', '44444444-0000-0000-0000-000000000007', '22222222-0000-0000-0000-000000000001', '100 mg', 'Capsule', 'Oral', true),
('55555555-0000-0000-0000-000000000009', 'Omez 20', '44444444-0000-0000-0000-000000000008', '22222222-0000-0000-0000-000000000003', '20 mg', 'Capsule', 'Oral', true),
('55555555-0000-0000-0000-000000000010', 'Pantocid 40', '44444444-0000-0000-0000-000000000009', '22222222-0000-0000-0000-000000000002', '40 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000011', 'Emeset 4', '44444444-0000-0000-0000-000000000010', '22222222-0000-0000-0000-000000000001', '4 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000012', 'Cetzine 10', '44444444-0000-0000-0000-000000000011', '22222222-0000-0000-0000-000000000005', '10 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000013', 'Asthalin Inhaler', '44444444-0000-0000-0000-000000000012', '22222222-0000-0000-0000-000000000001', '100 mcg', 'Inhaler', 'Inhalation', true),
('55555555-0000-0000-0000-000000000014', 'Glycomet 500', '44444444-0000-0000-0000-000000000013', '22222222-0000-0000-0000-000000000004', '500 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000015', 'Amlopres 5', '44444444-0000-0000-0000-000000000014', '22222222-0000-0000-0000-000000000001', '5 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000016', 'Losacar 50', '44444444-0000-0000-0000-000000000015', '22222222-0000-0000-0000-000000000006', '50 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000017', 'Telma 40', '44444444-0000-0000-0000-000000000016', '22222222-0000-0000-0000-000000000005', '40 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000018', 'Atorva 10', '44444444-0000-0000-0000-000000000017', '22222222-0000-0000-0000-000000000006', '10 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000019', 'Ecosprin 75', '44444444-0000-0000-0000-000000000018', '22222222-0000-0000-0000-000000000004', '75 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000020', 'Clopilet 75', '44444444-0000-0000-0000-000000000019', '22222222-0000-0000-0000-000000000002', '75 mg', 'Tablet', 'Oral', true),
('55555555-0000-0000-0000-000000000021', 'Thyronorm 100', '44444444-0000-0000-0000-000000000020', '22222222-0000-0000-0000-000000000004', '100 mcg', 'Tablet', 'Oral', true)
ON CONFLICT (id) DO NOTHING;

-- Medicine Classifications Junction
INSERT INTO public.medicine_classifications (medicine_id, class_id, is_primary) VALUES
('44444444-0000-0000-0000-000000000001', '33333333-0000-0000-0000-000000000001', true),
('44444444-0000-0000-0000-000000000002', '33333333-0000-0000-0000-000000000002', true),
('44444444-0000-0000-0000-000000000003', '33333333-0000-0000-0000-000000000002', true),
('44444444-0000-0000-0000-000000000004', '33333333-0000-0000-0000-000000000007', true),
('44444444-0000-0000-0000-000000000005', '33333333-0000-0000-0000-000000000007', true),
('44444444-0000-0000-0000-000000000006', '33333333-0000-0000-0000-000000000008', true),
('44444444-0000-0000-0000-000000000007', '33333333-0000-0000-0000-000000000009', true),
('44444444-0000-0000-0000-000000000008', '33333333-0000-0000-0000-000000000003', true),
('44444444-0000-0000-0000-000000000009', '33333333-0000-0000-0000-000000000003', true),
('44444444-0000-0000-0000-000000000010', '33333333-0000-0000-0000-000000000011', true),
('44444444-0000-0000-0000-000000000011', '33333333-0000-0000-0000-000000000012', true),
('44444444-0000-0000-0000-000000000012', '33333333-0000-0000-0000-000000000013', true),
('44444444-0000-0000-0000-000000000013', '33333333-0000-0000-0000-000000000010', true),
('44444444-0000-0000-0000-000000000014', '33333333-0000-0000-0000-000000000005', true),
('44444444-0000-0000-0000-000000000015', '33333333-0000-0000-0000-000000000004', true),
('44444444-0000-0000-0000-000000000016', '33333333-0000-0000-0000-000000000004', true),
('44444444-0000-0000-0000-000000000017', '33333333-0000-0000-0000-000000000006', true),
('44444444-0000-0000-0000-000000000018', '33333333-0000-0000-0000-000000000014', true),
('44444444-0000-0000-0000-000000000019', '33333333-0000-0000-0000-000000000014', true),
('44444444-0000-0000-0000-000000000020', '33333333-0000-0000-0000-000000000015', true)
ON CONFLICT (medicine_id, class_id) DO NOTHING;

-- 29 Core Medical Terms
INSERT INTO public.medical_terms (term, simple_definition, clinical_definition, hindi_explanation, hinglish_explanation, pronunciation) VALUES
('Analgesic', 'A drug that relieves pain.', 'An agent that selectively alleviates pain without causing loss of consciousness.', 'Dard nivarak davai.', 'Pain ya dard ko kam ya gayab karne wali medicine.', 'an-al-JEE-zik'),
('Antipyretic', 'A medicine that reduces fever.', 'A substance that reduces elevated core body temperature by acting on the hypothalamic thermoregulatory center.', 'Bukhar kam karne wali davai.', 'Fever / bukhar ko kam karne wali medicine.', 'an-tee-pye-RET-ik'),
('NSAID', 'Non-Steroidal Anti-Inflammatory Drug.', 'Non-steroidal pharmacological agent inhibiting cyclooxygenase (COX) enzymes, reducing pain, fever, and inflammation.', 'Gair-steroidal soojan-rodhi davai.', 'Bina steroid ke dard aur soojan kam karne wali standard medicine.', 'EN-sed'),
('Antibiotic', 'A medicine that kills or stops bacteria.', 'A microbial substance or synthetic agent that inhibits bacterial cell growth or causes bacterial lysis.', 'Jeevanu-rodhi davai.', 'Bacterial infection ko khatam ya rokne wali medicine.', 'an-ti-bye-OT-ik'),
('Antiviral', 'A medicine that stops viruses from multiplying.', 'An agent that inhibits specific steps in viral replication cycles within host cells.', 'Vishanu-rodhi davai.', 'Virus ke spread aur infection ko rokne wali medicine.', 'an-ti-VYE-ral'),
('Antifungal', 'A medicine used to treat fungal infections.', 'A pharmaceutical agent that selectively destroys fungal pathogens or inhibits their membrane/wall synthesis.', 'Fungus-rodhi davai.', 'Daad, khaj ya fungal infections ko thik karne wali medicine.', 'an-ti-FUNG-gal'),
('Antihistamine', 'A drug that relieves allergic symptoms.', 'A competitive antagonist of histamine H1 receptors that suppresses allergic and anaphylactoid manifestations.', 'Allergy-rodhi davai.', 'Allergy, chheenk aur itching ko block karne wali medicine.', 'an-ti-HIS-tuh-meen'),
('Antacid', 'A medicine that neutralizes stomach acid.', 'A basic inorganic chemical substance that directly neutralizes gastric hydrochloric acid in the stomach lumen.', 'Pet ke acid ko shaant karne wali davai.', 'Pet ki jalan aur acidity ko direct neutralize karne wali medicine.', 'ant-ASS-id'),
('PPI', 'Proton Pump Inhibitor for severe acidity.', 'Substituted benzimidazole that irreversibly inhibits gastric H+/K+ ATPase, producing profound acid suppression.', 'Stomach acid pump ko band karne wali davai.', 'Pet ke acid pump ko block karke acidity rokne wali long-lasting medicine.', 'P-P-I'),
('Diuretic', 'A medicine that increases urine output to remove water.', 'An agent that increases the rate of urine formation and sodium excretion by the kidneys.', 'Peshab badhane wali davai.', 'Body se excess water aur salt nikal kar BP aur swelling kam karne wali medicine.', 'dye-yoo-RET-ik'),
('Beta Blocker', 'A medicine that slows heart rate and lowers BP.', 'An antagonist of beta-adrenergic receptors, reducing cardiac workload, heart rate, and contractility.', 'Heart rate aur BP control karne wali davai.', 'Heart par stress aur high BP kam karne wali heart-protective medicine.', 'BAY-tuh BLOK-er'),
('ACE Inhibitor', 'A medicine that relaxes blood vessels by blocking ACE.', 'An agent that inhibits Angiotensin-Converting Enzyme, preventing formation of vasoconstrictor Angiotensin II.', 'Blood vessels ko chouda karne wali BP medicine.', 'Angiotensin enzyme ko rok kar blood pressure kam karne wali medicine.', 'A-C-E In-hib-i-ter'),
('ARB', 'Angiotensin II Receptor Blocker.', 'Selective antagonist of Angiotensin II AT1 receptors on vascular smooth muscle and adrenal glands.', 'AT1 receptor blocker BP davai.', 'Angiotensin II ke receptor ko block karke BP relax karne wali medicine.', 'A-R-B'),
('Calcium Channel Blocker', 'A medicine that dilates blood vessels by blocking calcium.', 'An inhibitor of L-type voltage-sensitive calcium channels in cardiac and vascular smooth muscle.', 'Blood vessels relax karne wali CCB davai.', 'Calcium entry ko rok kar blood vessels kholne aur BP kam karne wali medicine.', 'KAL-see-um CHAN-el BLOK-er'),
('Anticoagulant', 'A medicine that slows down blood clotting.', 'A substance that inhibits the coagulation cascade and prevents fibrin clot formation.', 'Khoon patla karne wali davai.', 'Khoon ke clot banne ki process ko rokne wali medicine.', 'an-tee-ko-AG-yoo-lunt'),
('Antiplatelet', 'A medicine preventing platelets from sticking together.', 'An agent that inhibits platelet activation, adhesion, or aggregation, preventing arterial thrombi.', 'Platelet ko chipakne se rokne wali davai.', 'Blood vessels mein arterial clot aur heart attack se bachane wali medicine.', 'an-tee-PLAYT-let'),
('Statin', 'A medicine that lowers bad cholesterol.', 'A competitive inhibitor of HMG-CoA reductase that drastically reduces hepatic LDL-cholesterol synthesis.', 'Cholesterol kam karne wali davai.', 'Liver mein bad cholesterol (LDL) ki production ko rokne wali standard medicine.', 'STAT-in'),
('Corticosteroid', 'A potent steroid that reduces severe inflammation.', 'A synthetic steroid hormone that mimics glucocorticoids, suppressing immune responses and cytokine expression.', 'Shaktishali soojan-rodhi steroid.', 'Powerful steroid jo severe allergy, asthma aur inflammation ko control karta hai.', 'kor-tih-ko-STEER-oyd'),
('Bronchodilator', 'A medicine that opens up airways for breathing.', 'An agent that causes widening of the lumina of the bronchial passages by relaxing airway smooth muscle.', 'Saans ki nali kholne wali davai.', 'Asthma aur saans fulne par airway ko kholne wali fast relief medicine.', 'brong-ko-dye-LAY-ter'),
('ADME', 'Absorption, Distribution, Metabolism, and Excretion.', 'The four primary pharmacokinetic disposition processes that determine drug concentration in the body over time.', 'Davai ka body mein absorption, failna, pachna aur bahar nikalna.', 'Drug body mein kaise enter hoti hai, distribute hoti hai, metabolize hoti hai aur excrete hoti hai.', 'A-D-M-E'),
('Pharmacokinetics', 'What the body does to the drug.', 'The study of the time course of drug absorption, distribution, metabolism, and excretion in the biological system.', 'Shareer davai ke sath kya karta hai.', 'Drug body ke andar enter hone se bahar nikalne tak kaise move karti hai.', 'far-muh-ko-kih-NET-iks'),
('Pharmacodynamics', 'What the drug does to the body.', 'The biochemical, physiological, and molecular effects of drugs on the body and their mechanisms of action.', 'Davai shareer par kya asar karti hai.', 'Drug body ke receptors aur organs par kya effect aur changes produce karti hai.', 'far-muh-ko-dye-NAM-iks'),
('Agonist', 'A drug that binds and activates a receptor.', 'A chemical entity that binds to a specific biological receptor and activates it to produce a physiological response.', 'Receptor ko activate karne wali davai.', 'Receptor par bind hokar natural signal jaisa response start karne wala compound.', 'AG-uh-nist'),
('Antagonist', 'A drug that binds and blocks a receptor.', 'A substance that binds to a specific receptor and inhibits or prevents the action of an agonist.', 'Receptor ko block karne wali davai.', 'Receptor ko block karke kisi chemical ya hormone ke action ko rokne wala compound.', 'an-TAG-uh-nist'),
('Receptor', 'A molecular lock on a cell that drugs bind to.', 'A specialized protein molecule on or within a cell that selectively recognizes and binds specific chemical signaling ligands.', 'Cell ka target lock.', 'Cell ka molecular lock jisme drug bind hokar apna action trigger karti hai.', 'rih-SEP-ter'),
('Half-life', 'Time needed for drug concentration to drop by half.', 'The time required for the plasma concentration of a drug in the body to decrease by 50%.', 'Davai ki matra aadhi hone ka samay.', 'Blood mein drug ki concentration aadhi (50%) reh jane mein kitna time lagta hai.', 'HAF-lyfe'),
('Bioavailability', 'Percentage of medicine that reaches the bloodstream.', 'The fraction and rate of an administered dose of unchanged drug that reaches the systemic circulation.', 'Khoon mein pahunchne wali davai ka pratishat.', 'Khaayi gayi medicine ka kitna percent actual mein blood stream mein absorb hota hai.', 'bye-o-uh-vay-luh-BIL-ih-tee'),
('Clearance', 'Volume of blood cleared of drug per unit time.', 'The volume of plasma or blood from which a drug is completely removed per unit time by metabolism or excretion.', 'Shareer se davai saaf hone ki dar.', 'Body ke liver aur kidney dwara per minute kitna blood drug-free kiya jata hai.', 'KLEER-uns'),
('Volume of Distribution', 'Apparent space in body into which drug distributes.', 'The theoretical volume of fluid into which the total amount of drug administered would need to be dissolved to equal plasma concentration.', 'Davai shareer ke tissue mein kitni failti hai.', 'Theoretical volume jo batata hai ki drug blood mein rehti hai ya body tissues mein deep chali jati hai.', 'VOL-yoom of dis-trih-BYOO-shun')
ON CONFLICT (term) DO NOTHING;
